# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  auth:
    description: 'AUTH ID of user'
    required: true
    default: 1
outputs:
  specurl:
    description: 'Name des Pokemons'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.auth }}
